### PR TITLE
P5R Animations automatic backport

### PR DESCRIPTION
**Pull request by Elvagan**
Hello, 

I couldn't contact you by other means so let's discuss here :)
Long story short, I forked GFDStudio to try to understand how modding works in P5 and I ended up making a version that can backport P5R animations.

I discussed a lot with Scartlz (from your server) and he helped me to figure out some things, once I was done he advised me to send a PR on the main repo so here I am :) I don't know if you heard about this fork so I'll detail the process (i'll probably say things you already know though).

P5R introduced two new Animation controller types: 34 and 35. I figured that 35 is actually a Rotation+Scale controller and someone (deathchaos also from your server) confirmed me that 34 is a Position+Scale controller.
P5 is not able to use these new types so what I did was take the separated new controllers (it could be NodrPHalf/NodeRHalf/NodeSHalf or NodePRHalf/NodeSHalf, ... any combination actually) and merging them into a NodePRSHalf layer that P5 can understand. The implementation of this is in AnimationController.cs

I added the support of these 2 new types in PRSKeyType.cs and KeyType.cs and also a little in AnimationLayer.cs

The changes in AnimationConverter.cs are to avoid a null pointer exception I got when importing some FBX animations.

The change in TextureDecoder.cs is just removing an unused variable.

And finally the rest is to support reading P5R stuff as it shares VersionID with Catherine Full Body. We lose the compatibility but I let some variables if we want to put it back later (will probably require to set a parameter from the UI like a switch between P5R and Catherine), or maybe if there is a way to tell from the files directly I'd be happy to hear about that.

I don't know if you are ok with the fact that it automatically converts animations maybe you would have preferred a "Tools" behavior with a batch convert. I'm actually thinking about implementing it but it will take some times as I need to figure out how WinForms works, I'm more used to Wpf actually :D. 
The idea was to provide the backport feature as soon as possible so people can use it, but if you prefer to wait until I'm done with this tell me.

I'm open to remarks so if you would like things to be coded differently don't hesitate.

Cheers

### CODE REVIEW

**Comment by TGEnigma** [comment]
Thanks for the contribution.
Looks fine for the most part, but like you mentioned I'd prefer if this conversion was optional and could be used throug a context menu item on the animation pack/animation in the UI.
The other thing I don't agree with is are the 'IsSet...' properties on the PRS keyframes. I don't feel like they're necessary to add considering the 'Use....' properties already exist. If they differ in some way I'd suggest keeping track of the state in the function.

**Comment by Elvagan** [comment]
Alright I'll come back to you once the feature is tied to a context menu.

For the other part, I concede that it's sad to add a Properties that will only be used in one function, I'll try to find an alternative. 
But I don't get what are the "Use..." properties you talk about, just to be sure you mean the "Has..." properties? Because the only "Use..." in the PRSkeys is UseScaleVectors but I'm pretty sure you are not talking about that.

**Comment by TGEnigma** [comment]
Sorry, I meant the "Has..." properties. Considering you added new types, you should probably modify those properties to reflect what components they contain. I figure this is also probably all you'd really need in the merging function.

**Comment by Elvagan** [comment]
Hello,

Moving the feature was easier than I thought :)

New/Modified stuff from last time is mainly in AnimationController.cs and PRSKey.cs (and some in the Forms for UI integration of course).

So now the conversion is not automatically done, you access it on the animation pack with "Tools -> Convert to P5" or via the top menu as a batch convert with "Tools -> Convert P5R animations to P5 in directory". I used the batch retarget as a template as it's almost the same thing.

About the other points, i refactored my Convert method in AnimationController.cs, it is now more concise and, i hope, clearer. I modified the Has... properties to reflect what has really been set in the key, I hope you are ok with these changes ^^.

If there are others things that doesn't match tell me.

Cheers

**Pull request merged**
